# 
apiVersion: v1
kind: Pod
metadata:
  name: wasm-test
spec:
  containers:
    - name: as-test
      image: localhost:5000/as-test:latest
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "250m"
          memory: "128Mi"
  tolerations:
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoSchedule"